### ISSUE TITLE
Рецензия 

### ISSUE THREAD

**Issue by komendantid** [medvedevmo/NewYearQuest#1]
Название игры, автор: “NewYearQuest”, Медведев Андрей
Readme - дает ли описание правильное представление о проекте, оцените оформление файла Readдает, все нормально
Карта игры - есть ли карта, ее оформление: есть, выполнена хорошо
Оцените оформление кода программы. Есть ли комментарии, помогают ли они пониманию: комментариев мало, можно сказать, что совсем нет, код программы нормальный 
Есть ли в коде программы строки, которые непонятны. Используются ли неизвестные (неизученные) конструкции: непонятны некоторые строчки из-за того, что используется неизученные конструкции 
Работоспособность программы - работает или нет, если программа не работает, то какую критическую ошибку выдает (скопировать ошибку): работает
Общее впечатление о программе: нормально
Пожелания и советы автору программы: подкорректировать возможные ответы на вопросы

**Comment by medvedevmo** [comment]
Где нужно сделать больше комментариев и какие строчки не понятны?
Неизученные конструкции только из библиотек requests, BeautifulSoup, можно прочитать их документацию:
requests - https://pypi.org/project/requests/
beautifulsoup - https://pypi.org/project/beautifulsoup4/
